# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20160520_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='beer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='brewer_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
