# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20160520_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='test_field',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
