# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_rating_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='test_field',
        ),
    ]
