# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_remove_rating_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='brewer_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='notes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female'), (b'U', b'Unisex/Parody')], max_length=50),
        ),
    ]
