# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_auto_20160522_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=50),
        ),
    ]
