# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 02:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0015_auto_20160523_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(10)]),
        ),
    ]
